steps:

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/vishakha-403211/test-tf'
      - '--build-arg'
      - 'GIT_COMMIT=$(cat ./git_commit_sha.txt)'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'asia-south1-docker.pkg.dev/vishakha-403211/test-tf'

options:
  logging: CLOUD_LOGGING_ONLY
